
resources:
- app.yaml
- ingress.yaml
- frontend.yaml

secretGenerator:
- name: app-secrets
  options:
    disableNameSuffixHash: true
  envs:
  - secrets.env

commonAnnotations:
  gitCommit: ${GIT_COMMIT}

commonLabels:
  appName: ${PROJECT_NAME}